---
version: 1.0
name: Corbeetje.NL
description: Corbeetje.NL
url: http://corbeetje.nl/
timezone: Europe/Amsterdam

google_analytics_id: UA-xxxxxxxx-x
google_site_verification: 

sass:
  style: compressed

exclude:
- ".gitignore"
- CNAME
- readme.md